// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnMaC8ViuhGkc2qF8D9aQ8-m1bkZUnBHY',
    appId: '1:135373657576:web:671dcb7828ec725c12005d',
    messagingSenderId: '135373657576',
    projectId: 'chatbox-3d921',
    authDomain: 'chatbox-3d921.firebaseapp.com',
    storageBucket: 'chatbox-3d921.appspot.com',
    measurementId: 'G-V104RG1NPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqH1nyiLIP54lMfIZxxhj33e5_SkoTpLo',
    appId: '1:135373657576:android:b118b4284ff97fae12005d',
    messagingSenderId: '135373657576',
    projectId: 'chatbox-3d921',
    storageBucket: 'chatbox-3d921.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCq_1JvGiKCVHjS2nCi2-eHA-RWkzujK3Q',
    appId: '1:135373657576:ios:02f4245f7a70c51e12005d',
    messagingSenderId: '135373657576',
    projectId: 'chatbox-3d921',
    storageBucket: 'chatbox-3d921.appspot.com',
    iosClientId: '135373657576-0ottn9qnjk9teg4o7okphrr2d8mbbfuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCq_1JvGiKCVHjS2nCi2-eHA-RWkzujK3Q',
    appId: '1:135373657576:ios:02f4245f7a70c51e12005d',
    messagingSenderId: '135373657576',
    projectId: 'chatbox-3d921',
    storageBucket: 'chatbox-3d921.appspot.com',
    iosClientId: '135373657576-0ottn9qnjk9teg4o7okphrr2d8mbbfuh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
